ревизия Makefile

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -640,6 +640,10 @@ INSTALL_DATA
 AR
 RANLIB
 MKDIR
+SASL
+SASL_LIBS
+WITH_MYSQL
+MYSQL_LIBS
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -1228,7 +1232,10 @@ if test -n "$ac_init_help"; then
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-sasl=TYPE        switch SASL library (cyrus, gnu, none)
   --with-gsasl=PREFIX     GNU SASL library
+  --with-cyrus-sasl=PREFIX
+                          Cyrus SASL library
   --with-mysql=PREFIX     MySQL client library
   --with-udns=PREFIX      UDNS (DNS Resolver Library)
 
@@ -4205,6 +4212,42 @@ else
 fi
 
 
+SASL=none
+SASL_LIBS=""
+
+# Check whether --with-sasl was given.
+if test "${with_sasl+set}" = set; then
+  withval=$with_sasl;
+		SASL=$withval
+		case "$SASL" in
+		gnu)
+			cat >>confdefs.h <<\_ACEOF
+#define WITH_GNU_SASL 1
+_ACEOF
+
+			SASL_LIBS="-lgsasl"
+			;;
+		cyrus)
+			cat >>confdefs.h <<\_ACEOF
+#define WITH_CYRUS_SASL 1
+_ACEOF
+
+			SASL_LIBS="-lsasl2"
+			;;
+		none)
+			;;
+		*)
+			{ { echo "$as_me:$LINENO: error: switch SASL library (cyrus, gnu, none)" >&5
+echo "$as_me: error: switch SASL library (cyrus, gnu, none)" >&2;}
+   { (exit 1); exit 1; }; }
+			;;
+		esac
+
+fi
+
+
+
+
 
 # Check whether --with-gsasl was given.
 if test "${with_gsasl+set}" = set; then
@@ -4214,7 +4257,6 @@ if test "${with_gsasl+set}" = set; then
 
 fi
 
-# TODO AC_CHECK_HEADER(gsasl.h, [], [AC_ERROR(GNU SASL library required)])
 
 { echo "$as_me:$LINENO: checking for main in -lgsasl" >&5
 echo $ECHO_N "checking for main in -lgsasl... $ECHO_C" >&6; }
@@ -4279,22 +4321,112 @@ _ACEOF
   LIBS="-lgsasl $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: GNU SASL library required" >&5
+
+		if test "$SASL" = "gnu"; then
+			{ { echo "$as_me:$LINENO: error: GNU SASL library required" >&5
 echo "$as_me: error: GNU SASL library required" >&2;}
    { (exit 1); exit 1; }; }
+		fi
+
 fi
 
 
 
-# Check whether --with-mysql was given.
-if test "${with_mysql+set}" = set; then
-  withval=$with_mysql;
+# Check whether --with-cyrus-sasl was given.
+if test "${with_cyrus_sasl+set}" = set; then
+  withval=$with_cyrus_sasl;
 		CPPFLAGS="$CPPFLAGS  -I$withval/include"
 		LDFLAGS="$LDFLAGS -L$withval/lib -Wl,-rpath=$withval/lib"
 
 fi
 
-# TODO AC_CHECK_HEADER(mysql.h, [], [AC_ERROR(MySQL client library required)])
+
+{ echo "$as_me:$LINENO: checking for main in -lsasl2" >&5
+echo $ECHO_N "checking for main in -lsasl2... $ECHO_C" >&6; }
+if test "${ac_cv_lib_sasl2_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsasl2  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_sasl2_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_sasl2_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_sasl2_main" >&5
+echo "${ECHO_T}$ac_cv_lib_sasl2_main" >&6; }
+if test $ac_cv_lib_sasl2_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBSASL2 1
+_ACEOF
+
+  LIBS="-lsasl2 $LIBS"
+
+else
+
+		if test "$SASL" = "cyrus"; then
+			{ { echo "$as_me:$LINENO: error: Cyrus SASL library required" >&5
+echo "$as_me: error: Cyrus SASL library required" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+
+fi
+
+
+WITH_MYSQL=no
+MYSQL_LIBS=""
+
+# Check whether --with-mysql was given.
+if test "${with_mysql+set}" = set; then
+  withval=$with_mysql;
+		if test "$withval" != "yes"; then
+			CPPFLAGS="$CPPFLAGS  -I$withval/include"
+			LDFLAGS="$LDFLAGS -L$withval/lib -Wl,-rpath=$withval/lib"
+		fi
+		WITH_MYSQL=yes
+
+fi
 
 { echo "$as_me:$LINENO: checking for mysql_real_connect in -lmysqlclient_r" >&5
 echo $ECHO_N "checking for mysql_real_connect in -lmysqlclient_r... $ECHO_C" >&6; }
@@ -4358,92 +4490,22 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlclient_r_mysql_real_connect" >&5
 echo "${ECHO_T}$ac_cv_lib_mysqlclient_r_mysql_real_connect" >&6; }
 if test $ac_cv_lib_mysqlclient_r_mysql_real_connect = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBMYSQLCLIENT_R 1
-_ACEOF
 
-  LIBS="-lmysqlclient_r $LIBS"
+		MYSQL_LIBS="-lmysqlclient_r"
+		WITH_MYSQL="yes"
 
 else
-  { { echo "$as_me:$LINENO: error: MySQL client library required" >&5
-echo "$as_me: error: MySQL client library required" >&2;}
+
+		if test "$WITH_MYSQL" = "yes"; then
+			{ { echo "$as_me:$LINENO: error: MySQL client library not found" >&5
+echo "$as_me: error: MySQL client library not found" >&2;}
    { (exit 1); exit 1; }; }
+		fi
+
 fi
 
 
-{ echo "$as_me:$LINENO: checking for mysql_real_query in -lmysqlclient_r" >&5
-echo $ECHO_N "checking for mysql_real_query in -lmysqlclient_r... $ECHO_C" >&6; }
-if test "${ac_cv_lib_mysqlclient_r_mysql_real_query+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lmysqlclient_r  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
 
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char mysql_real_query ();
-int
-main ()
-{
-return mysql_real_query ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_mysqlclient_r_mysql_real_query=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_cv_lib_mysqlclient_r_mysql_real_query=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlclient_r_mysql_real_query" >&5
-echo "${ECHO_T}$ac_cv_lib_mysqlclient_r_mysql_real_query" >&6; }
-if test $ac_cv_lib_mysqlclient_r_mysql_real_query = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBMYSQLCLIENT_R 1
-_ACEOF
-
-  LIBS="-lmysqlclient_r $LIBS"
-
-else
-  { { echo "$as_me:$LINENO: error: MySQL client library required" >&5
-echo "$as_me: error: MySQL client library required" >&2;}
-   { (exit 1); exit 1; }; }
-fi
 
 
 
@@ -4456,12 +4518,6 @@ if test "${with_udns+set}" = set; then
 fi
 
 # TODO AC_CHECK_LIB(udns, main, [], [AC_ERROR(UDNS (DNS Resolver Library) required)])
-
-# Checks for libraries.
-
-# Checks for header files.
-
-# Checks for typedefs, structures, and compiler characteristics.
 
 # Checks for library functions.
 { echo "$as_me:$LINENO: checking for gai_strerror" >&5
@@ -5233,11 +5289,15 @@ INSTALL_DATA!$INSTALL_DATA$ac_delim
 AR!$AR$ac_delim
 RANLIB!$RANLIB$ac_delim
 MKDIR!$MKDIR$ac_delim
+SASL!$SASL$ac_delim
+SASL_LIBS!$SASL_LIBS$ac_delim
+WITH_MYSQL!$WITH_MYSQL$ac_delim
+MYSQL_LIBS!$MYSQL_LIBS$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 64; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 68; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
